// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/proto/log.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Matches the models.Log structure exactly
type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ResourceId    string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_pkg_proto_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_pkg_proto_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_log_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogRequest          `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatchRequest) Reset() {
	*x = LogBatchRequest{}
	mi := &file_pkg_proto_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatchRequest) ProtoMessage() {}

func (x *LogBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatchRequest.ProtoReflect.Descriptor instead.
func (*LogBatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_log_proto_rawDescGZIP(), []int{2}
}

func (x *LogBatchRequest) GetLogs() []*LogRequest {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_pkg_proto_log_proto protoreflect.FileDescriptor

const file_pkg_proto_log_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/proto/log.proto\x12\n" +
	"logservice\"{\n" +
	"\n" +
	"LogRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\"A\n" +
	"\vLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x0fLogBatchRequest\x12*\n" +
	"\x04logs\x18\x01 \x03(\v2\x16.logservice.LogRequestR\x04logs2J\n" +
	"\n" +
	"LogService\x12<\n" +
	"\aSendLog\x12\x16.logservice.LogRequest\x1a\x17.logservice.LogResponse\"\x00B\x18Z\x16logingrestor/pkg/protob\x06proto3"

var (
	file_pkg_proto_log_proto_rawDescOnce sync.Once
	file_pkg_proto_log_proto_rawDescData []byte
)

func file_pkg_proto_log_proto_rawDescGZIP() []byte {
	file_pkg_proto_log_proto_rawDescOnce.Do(func() {
		file_pkg_proto_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_log_proto_rawDesc), len(file_pkg_proto_log_proto_rawDesc)))
	})
	return file_pkg_proto_log_proto_rawDescData
}

var file_pkg_proto_log_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_log_proto_goTypes = []any{
	(*LogRequest)(nil),      // 0: logservice.LogRequest
	(*LogResponse)(nil),     // 1: logservice.LogResponse
	(*LogBatchRequest)(nil), // 2: logservice.LogBatchRequest
}
var file_pkg_proto_log_proto_depIdxs = []int32{
	0, // 0: logservice.LogBatchRequest.logs:type_name -> logservice.LogRequest
	0, // 1: logservice.LogService.SendLog:input_type -> logservice.LogRequest
	1, // 2: logservice.LogService.SendLog:output_type -> logservice.LogResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_log_proto_init() }
func file_pkg_proto_log_proto_init() {
	if File_pkg_proto_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_log_proto_rawDesc), len(file_pkg_proto_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_log_proto_goTypes,
		DependencyIndexes: file_pkg_proto_log_proto_depIdxs,
		MessageInfos:      file_pkg_proto_log_proto_msgTypes,
	}.Build()
	File_pkg_proto_log_proto = out.File
	file_pkg_proto_log_proto_goTypes = nil
	file_pkg_proto_log_proto_depIdxs = nil
}
