# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11log_service.proto\x12\nlogservice\"T\n\nLogRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x13\n\x0bresource_id\x18\x04 \x01(\t\"/\n\x0bLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"7\n\x0fLogBatchRequest\x12$\n\x04logs\x18\x01 \x03(\x0b\x32\x16.logservice.LogRequest2J\n\nLogService\x12<\n\x07SendLog\x12\x16.logservice.LogRequest\x1a\x17.logservice.LogResponse\"\x00\x42\x18Z\x16logingrestor/pkg/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\026logingrestor/pkg/proto'
  _LOGREQUEST._serialized_start=33
  _LOGREQUEST._serialized_end=117
  _LOGRESPONSE._serialized_start=119
  _LOGRESPONSE._serialized_end=166
  _LOGBATCHREQUEST._serialized_start=168
  _LOGBATCHREQUEST._serialized_end=223
  _LOGSERVICE._serialized_start=225
  _LOGSERVICE._serialized_end=299
# @@protoc_insertion_point(module_scope)
