# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/proto/log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13pkg/proto/log.proto\x12\x03log\"S\n\nLogRequest\x12\r\n\x05level\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nresourceID\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"/\n\x0bLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2<\n\nLogService\x12.\n\x07SendLog\x12\x0f.log.LogRequest\x1a\x10.log.LogResponse\"\x00\x42\x18Z\x16logingrestor/pkg/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.proto.log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\026logingrestor/pkg/proto'
  _LOGREQUEST._serialized_start=28
  _LOGREQUEST._serialized_end=111
  _LOGRESPONSE._serialized_start=113
  _LOGRESPONSE._serialized_end=160
  _LOGSERVICE._serialized_start=162
  _LOGSERVICE._serialized_end=222
# @@protoc_insertion_point(module_scope)
